package com.platform.field.mapping.dao;

import com.platform.field.mapping.entity.BasedataI18n;
import com.platform.field.mapping.entity.BasedataI18nExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasedataI18nMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basedata_i18n
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    long countByExample(BasedataI18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basedata_i18n
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    int deleteByExample(BasedataI18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basedata_i18n
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    int insert(BasedataI18n record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basedata_i18n
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    int insertSelective(BasedataI18n record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basedata_i18n
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    List<BasedataI18n> selectByExample(BasedataI18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basedata_i18n
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") BasedataI18n record, @Param("example") BasedataI18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basedata_i18n
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    int updateByExample(@Param("record") BasedataI18n record, @Param("example") BasedataI18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basedata_i18n
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    int batchUpdateByPrimaryKeySelective(@Param("list") List<BasedataI18n> list, @Param("example") BasedataI18nExample example);
}