package com.platform.field.mapping.entity;

import com.platform.mybatis.plugin.common.base.BaseEntity;
import java.io.Serializable;

public class BasedataI18n extends BaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedata_i18n.ID
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedata_i18n.CN
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    private String cn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedata_i18n.TYPE
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedata_i18n.NICK
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    private String nick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedata_i18n.EN
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    private String en;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basedata_i18n
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedata_i18n.ID
     *
     * @return the value of basedata_i18n.ID
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedata_i18n.ID
     *
     * @param id the value for basedata_i18n.ID
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedata_i18n.CN
     *
     * @return the value of basedata_i18n.CN
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    public String getCn() {
        return cn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedata_i18n.CN
     *
     * @param cn the value for basedata_i18n.CN
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    public void setCn(String cn) {
        this.cn = cn == null ? null : cn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedata_i18n.TYPE
     *
     * @return the value of basedata_i18n.TYPE
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedata_i18n.TYPE
     *
     * @param type the value for basedata_i18n.TYPE
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedata_i18n.NICK
     *
     * @return the value of basedata_i18n.NICK
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedata_i18n.NICK
     *
     * @param nick the value for basedata_i18n.NICK
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedata_i18n.EN
     *
     * @return the value of basedata_i18n.EN
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    public String getEn() {
        return en;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedata_i18n.EN
     *
     * @param en the value for basedata_i18n.EN
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    public void setEn(String en) {
        this.en = en == null ? null : en.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basedata_i18n
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cn=").append(cn);
        sb.append(", type=").append(type);
        sb.append(", nick=").append(nick);
        sb.append(", en=").append(en);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basedata_i18n
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BasedataI18n other = (BasedataI18n) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCn() == null ? other.getCn() == null : this.getCn().equals(other.getCn()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getNick() == null ? other.getNick() == null : this.getNick().equals(other.getNick()))
            && (this.getEn() == null ? other.getEn() == null : this.getEn().equals(other.getEn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basedata_i18n
     *
     * @mbg.generated Mon Sep 03 17:21:33 GMT+08:00 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCn() == null) ? 0 : getCn().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getNick() == null) ? 0 : getNick().hashCode());
        result = prime * result + ((getEn() == null) ? 0 : getEn().hashCode());
        return result;
    }
}