package com.platform.field.mapping.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FieldNameExample {
    //tpl_field_name
    protected String orderByClause;

    //tpl_field_name
    protected boolean distinct;

    //tpl_field_name
    protected List<Criteria> oredCriteria;

    public FieldNameExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tpl_field_name
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFieldidIsNull() {
            addCriterion("FIELDID is null");
            return (Criteria) this;
        }

        public Criteria andFieldidIsNotNull() {
            addCriterion("FIELDID is not null");
            return (Criteria) this;
        }

        public Criteria andFieldidEqualTo(String value) {
            addCriterion("FIELDID =", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidNotEqualTo(String value) {
            addCriterion("FIELDID <>", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidGreaterThan(String value) {
            addCriterion("FIELDID >", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidGreaterThanOrEqualTo(String value) {
            addCriterion("FIELDID >=", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidLessThan(String value) {
            addCriterion("FIELDID <", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidLessThanOrEqualTo(String value) {
            addCriterion("FIELDID <=", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidLike(String value) {
            addCriterion("FIELDID like", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidNotLike(String value) {
            addCriterion("FIELDID not like", value, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidIn(List<String> values) {
            addCriterion("FIELDID in", values, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidNotIn(List<String> values) {
            addCriterion("FIELDID not in", values, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidBetween(String value1, String value2) {
            addCriterion("FIELDID between", value1, value2, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldidNotBetween(String value1, String value2) {
            addCriterion("FIELDID not between", value1, value2, "fieldid");
            return (Criteria) this;
        }

        public Criteria andFieldCnIsNull() {
            addCriterion("FIELD_CN is null");
            return (Criteria) this;
        }

        public Criteria andFieldCnIsNotNull() {
            addCriterion("FIELD_CN is not null");
            return (Criteria) this;
        }

        public Criteria andFieldCnEqualTo(String value) {
            addCriterion("FIELD_CN =", value, "fieldCn");
            return (Criteria) this;
        }

        public Criteria andFieldCnNotEqualTo(String value) {
            addCriterion("FIELD_CN <>", value, "fieldCn");
            return (Criteria) this;
        }

        public Criteria andFieldCnGreaterThan(String value) {
            addCriterion("FIELD_CN >", value, "fieldCn");
            return (Criteria) this;
        }

        public Criteria andFieldCnGreaterThanOrEqualTo(String value) {
            addCriterion("FIELD_CN >=", value, "fieldCn");
            return (Criteria) this;
        }

        public Criteria andFieldCnLessThan(String value) {
            addCriterion("FIELD_CN <", value, "fieldCn");
            return (Criteria) this;
        }

        public Criteria andFieldCnLessThanOrEqualTo(String value) {
            addCriterion("FIELD_CN <=", value, "fieldCn");
            return (Criteria) this;
        }

        public Criteria andFieldCnLike(String value) {
            addCriterion("FIELD_CN like", value, "fieldCn");
            return (Criteria) this;
        }

        public Criteria andFieldCnNotLike(String value) {
            addCriterion("FIELD_CN not like", value, "fieldCn");
            return (Criteria) this;
        }

        public Criteria andFieldCnIn(List<String> values) {
            addCriterion("FIELD_CN in", values, "fieldCn");
            return (Criteria) this;
        }

        public Criteria andFieldCnNotIn(List<String> values) {
            addCriterion("FIELD_CN not in", values, "fieldCn");
            return (Criteria) this;
        }

        public Criteria andFieldCnBetween(String value1, String value2) {
            addCriterion("FIELD_CN between", value1, value2, "fieldCn");
            return (Criteria) this;
        }

        public Criteria andFieldCnNotBetween(String value1, String value2) {
            addCriterion("FIELD_CN not between", value1, value2, "fieldCn");
            return (Criteria) this;
        }

        public Criteria andFieldEnIsNull() {
            addCriterion("FIELD_EN is null");
            return (Criteria) this;
        }

        public Criteria andFieldEnIsNotNull() {
            addCriterion("FIELD_EN is not null");
            return (Criteria) this;
        }

        public Criteria andFieldEnEqualTo(String value) {
            addCriterion("FIELD_EN =", value, "fieldEn");
            return (Criteria) this;
        }

        public Criteria andFieldEnNotEqualTo(String value) {
            addCriterion("FIELD_EN <>", value, "fieldEn");
            return (Criteria) this;
        }

        public Criteria andFieldEnGreaterThan(String value) {
            addCriterion("FIELD_EN >", value, "fieldEn");
            return (Criteria) this;
        }

        public Criteria andFieldEnGreaterThanOrEqualTo(String value) {
            addCriterion("FIELD_EN >=", value, "fieldEn");
            return (Criteria) this;
        }

        public Criteria andFieldEnLessThan(String value) {
            addCriterion("FIELD_EN <", value, "fieldEn");
            return (Criteria) this;
        }

        public Criteria andFieldEnLessThanOrEqualTo(String value) {
            addCriterion("FIELD_EN <=", value, "fieldEn");
            return (Criteria) this;
        }

        public Criteria andFieldEnLike(String value) {
            addCriterion("FIELD_EN like", value, "fieldEn");
            return (Criteria) this;
        }

        public Criteria andFieldEnNotLike(String value) {
            addCriterion("FIELD_EN not like", value, "fieldEn");
            return (Criteria) this;
        }

        public Criteria andFieldEnIn(List<String> values) {
            addCriterion("FIELD_EN in", values, "fieldEn");
            return (Criteria) this;
        }

        public Criteria andFieldEnNotIn(List<String> values) {
            addCriterion("FIELD_EN not in", values, "fieldEn");
            return (Criteria) this;
        }

        public Criteria andFieldEnBetween(String value1, String value2) {
            addCriterion("FIELD_EN between", value1, value2, "fieldEn");
            return (Criteria) this;
        }

        public Criteria andFieldEnNotBetween(String value1, String value2) {
            addCriterion("FIELD_EN not between", value1, value2, "fieldEn");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIsNull() {
            addCriterion("LAST_UPDATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIsNotNull() {
            addCriterion("LAST_UPDATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByEqualTo(String value) {
            addCriterion("LAST_UPDATED_BY =", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotEqualTo(String value) {
            addCriterion("LAST_UPDATED_BY <>", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByGreaterThan(String value) {
            addCriterion("LAST_UPDATED_BY >", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_UPDATED_BY >=", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLessThan(String value) {
            addCriterion("LAST_UPDATED_BY <", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("LAST_UPDATED_BY <=", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLike(String value) {
            addCriterion("LAST_UPDATED_BY like", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotLike(String value) {
            addCriterion("LAST_UPDATED_BY not like", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIn(List<String> values) {
            addCriterion("LAST_UPDATED_BY in", values, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotIn(List<String> values) {
            addCriterion("LAST_UPDATED_BY not in", values, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByBetween(String value1, String value2) {
            addCriterion("LAST_UPDATED_BY between", value1, value2, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotBetween(String value1, String value2) {
            addCriterion("LAST_UPDATED_BY not between", value1, value2, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("CREATED_BY like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("CREATED_BY not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CREATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CREATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("CREATED_TIME =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("CREATED_TIME <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("CREATED_TIME >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_TIME >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("CREATED_TIME <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_TIME <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("CREATED_TIME in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("CREATED_TIME not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("CREATED_TIME between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_TIME not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDatetimeIsNull() {
            addCriterion("LAST_UPDATED_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDatetimeIsNotNull() {
            addCriterion("LAST_UPDATED_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDatetimeEqualTo(Date value) {
            addCriterion("LAST_UPDATED_DATETIME =", value, "lastUpdatedDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDatetimeNotEqualTo(Date value) {
            addCriterion("LAST_UPDATED_DATETIME <>", value, "lastUpdatedDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDatetimeGreaterThan(Date value) {
            addCriterion("LAST_UPDATED_DATETIME >", value, "lastUpdatedDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATED_DATETIME >=", value, "lastUpdatedDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDatetimeLessThan(Date value) {
            addCriterion("LAST_UPDATED_DATETIME <", value, "lastUpdatedDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATED_DATETIME <=", value, "lastUpdatedDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDatetimeIn(List<Date> values) {
            addCriterion("LAST_UPDATED_DATETIME in", values, "lastUpdatedDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDatetimeNotIn(List<Date> values) {
            addCriterion("LAST_UPDATED_DATETIME not in", values, "lastUpdatedDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDatetimeBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATED_DATETIME between", value1, value2, "lastUpdatedDatetime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATED_DATETIME not between", value1, value2, "lastUpdatedDatetime");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DELETE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DELETE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(String value) {
            addCriterion("DELETE_FLAG =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(String value) {
            addCriterion("DELETE_FLAG <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(String value) {
            addCriterion("DELETE_FLAG >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(String value) {
            addCriterion("DELETE_FLAG >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(String value) {
            addCriterion("DELETE_FLAG <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(String value) {
            addCriterion("DELETE_FLAG <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLike(String value) {
            addCriterion("DELETE_FLAG like", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotLike(String value) {
            addCriterion("DELETE_FLAG not like", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<String> values) {
            addCriterion("DELETE_FLAG in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<String> values) {
            addCriterion("DELETE_FLAG not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(String value1, String value2) {
            addCriterion("DELETE_FLAG between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(String value1, String value2) {
            addCriterion("DELETE_FLAG not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tpl_field_name
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tpl_field_name
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}