package com.platform.field.mapping.entity;

import java.util.ArrayList;
import java.util.List;

public class PlatformFieldsExample {
    //PLATFORM_FIELDS
    protected String orderByClause;

    //PLATFORM_FIELDS
    protected boolean distinct;

    //PLATFORM_FIELDS
    protected List<Criteria> oredCriteria;

    public PlatformFieldsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PLATFORM_FIELDS
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFieldNameCnIsNull() {
            addCriterion("FIELD_NAME_CN is null");
            return (Criteria) this;
        }

        public Criteria andFieldNameCnIsNotNull() {
            addCriterion("FIELD_NAME_CN is not null");
            return (Criteria) this;
        }

        public Criteria andFieldNameCnEqualTo(String value) {
            addCriterion("FIELD_NAME_CN =", value, "fieldNameCn");
            return (Criteria) this;
        }

        public Criteria andFieldNameCnNotEqualTo(String value) {
            addCriterion("FIELD_NAME_CN <>", value, "fieldNameCn");
            return (Criteria) this;
        }

        public Criteria andFieldNameCnGreaterThan(String value) {
            addCriterion("FIELD_NAME_CN >", value, "fieldNameCn");
            return (Criteria) this;
        }

        public Criteria andFieldNameCnGreaterThanOrEqualTo(String value) {
            addCriterion("FIELD_NAME_CN >=", value, "fieldNameCn");
            return (Criteria) this;
        }

        public Criteria andFieldNameCnLessThan(String value) {
            addCriterion("FIELD_NAME_CN <", value, "fieldNameCn");
            return (Criteria) this;
        }

        public Criteria andFieldNameCnLessThanOrEqualTo(String value) {
            addCriterion("FIELD_NAME_CN <=", value, "fieldNameCn");
            return (Criteria) this;
        }

        public Criteria andFieldNameCnLike(String value) {
            addCriterion("FIELD_NAME_CN like", value, "fieldNameCn");
            return (Criteria) this;
        }

        public Criteria andFieldNameCnNotLike(String value) {
            addCriterion("FIELD_NAME_CN not like", value, "fieldNameCn");
            return (Criteria) this;
        }

        public Criteria andFieldNameCnIn(List<String> values) {
            addCriterion("FIELD_NAME_CN in", values, "fieldNameCn");
            return (Criteria) this;
        }

        public Criteria andFieldNameCnNotIn(List<String> values) {
            addCriterion("FIELD_NAME_CN not in", values, "fieldNameCn");
            return (Criteria) this;
        }

        public Criteria andFieldNameCnBetween(String value1, String value2) {
            addCriterion("FIELD_NAME_CN between", value1, value2, "fieldNameCn");
            return (Criteria) this;
        }

        public Criteria andFieldNameCnNotBetween(String value1, String value2) {
            addCriterion("FIELD_NAME_CN not between", value1, value2, "fieldNameCn");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andFieldNameEnIsNull() {
            addCriterion("FIELD_NAME_EN is null");
            return (Criteria) this;
        }

        public Criteria andFieldNameEnIsNotNull() {
            addCriterion("FIELD_NAME_EN is not null");
            return (Criteria) this;
        }

        public Criteria andFieldNameEnEqualTo(String value) {
            addCriterion("FIELD_NAME_EN =", value, "fieldNameEn");
            return (Criteria) this;
        }

        public Criteria andFieldNameEnNotEqualTo(String value) {
            addCriterion("FIELD_NAME_EN <>", value, "fieldNameEn");
            return (Criteria) this;
        }

        public Criteria andFieldNameEnGreaterThan(String value) {
            addCriterion("FIELD_NAME_EN >", value, "fieldNameEn");
            return (Criteria) this;
        }

        public Criteria andFieldNameEnGreaterThanOrEqualTo(String value) {
            addCriterion("FIELD_NAME_EN >=", value, "fieldNameEn");
            return (Criteria) this;
        }

        public Criteria andFieldNameEnLessThan(String value) {
            addCriterion("FIELD_NAME_EN <", value, "fieldNameEn");
            return (Criteria) this;
        }

        public Criteria andFieldNameEnLessThanOrEqualTo(String value) {
            addCriterion("FIELD_NAME_EN <=", value, "fieldNameEn");
            return (Criteria) this;
        }

        public Criteria andFieldNameEnLike(String value) {
            addCriterion("FIELD_NAME_EN like", value, "fieldNameEn");
            return (Criteria) this;
        }

        public Criteria andFieldNameEnNotLike(String value) {
            addCriterion("FIELD_NAME_EN not like", value, "fieldNameEn");
            return (Criteria) this;
        }

        public Criteria andFieldNameEnIn(List<String> values) {
            addCriterion("FIELD_NAME_EN in", values, "fieldNameEn");
            return (Criteria) this;
        }

        public Criteria andFieldNameEnNotIn(List<String> values) {
            addCriterion("FIELD_NAME_EN not in", values, "fieldNameEn");
            return (Criteria) this;
        }

        public Criteria andFieldNameEnBetween(String value1, String value2) {
            addCriterion("FIELD_NAME_EN between", value1, value2, "fieldNameEn");
            return (Criteria) this;
        }

        public Criteria andFieldNameEnNotBetween(String value1, String value2) {
            addCriterion("FIELD_NAME_EN not between", value1, value2, "fieldNameEn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PLATFORM_FIELDS
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PLATFORM_FIELDS
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}