package com.platform.field.mapping.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TableMappingExample {
    //tpl_table_mapping
    protected String orderByClause;

    //tpl_table_mapping
    protected boolean distinct;

    //tpl_table_mapping
    protected List<Criteria> oredCriteria;

    public TableMappingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tpl_table_mapping
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTableNameidIsNull() {
            addCriterion("TABLE_NAMEID is null");
            return (Criteria) this;
        }

        public Criteria andTableNameidIsNotNull() {
            addCriterion("TABLE_NAMEID is not null");
            return (Criteria) this;
        }

        public Criteria andTableNameidEqualTo(String value) {
            addCriterion("TABLE_NAMEID =", value, "tableNameid");
            return (Criteria) this;
        }

        public Criteria andTableNameidNotEqualTo(String value) {
            addCriterion("TABLE_NAMEID <>", value, "tableNameid");
            return (Criteria) this;
        }

        public Criteria andTableNameidGreaterThan(String value) {
            addCriterion("TABLE_NAMEID >", value, "tableNameid");
            return (Criteria) this;
        }

        public Criteria andTableNameidGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_NAMEID >=", value, "tableNameid");
            return (Criteria) this;
        }

        public Criteria andTableNameidLessThan(String value) {
            addCriterion("TABLE_NAMEID <", value, "tableNameid");
            return (Criteria) this;
        }

        public Criteria andTableNameidLessThanOrEqualTo(String value) {
            addCriterion("TABLE_NAMEID <=", value, "tableNameid");
            return (Criteria) this;
        }

        public Criteria andTableNameidLike(String value) {
            addCriterion("TABLE_NAMEID like", value, "tableNameid");
            return (Criteria) this;
        }

        public Criteria andTableNameidNotLike(String value) {
            addCriterion("TABLE_NAMEID not like", value, "tableNameid");
            return (Criteria) this;
        }

        public Criteria andTableNameidIn(List<String> values) {
            addCriterion("TABLE_NAMEID in", values, "tableNameid");
            return (Criteria) this;
        }

        public Criteria andTableNameidNotIn(List<String> values) {
            addCriterion("TABLE_NAMEID not in", values, "tableNameid");
            return (Criteria) this;
        }

        public Criteria andTableNameidBetween(String value1, String value2) {
            addCriterion("TABLE_NAMEID between", value1, value2, "tableNameid");
            return (Criteria) this;
        }

        public Criteria andTableNameidNotBetween(String value1, String value2) {
            addCriterion("TABLE_NAMEID not between", value1, value2, "tableNameid");
            return (Criteria) this;
        }

        public Criteria andTableCnIsNull() {
            addCriterion("TABLE_CN is null");
            return (Criteria) this;
        }

        public Criteria andTableCnIsNotNull() {
            addCriterion("TABLE_CN is not null");
            return (Criteria) this;
        }

        public Criteria andTableCnEqualTo(String value) {
            addCriterion("TABLE_CN =", value, "tableCn");
            return (Criteria) this;
        }

        public Criteria andTableCnNotEqualTo(String value) {
            addCriterion("TABLE_CN <>", value, "tableCn");
            return (Criteria) this;
        }

        public Criteria andTableCnGreaterThan(String value) {
            addCriterion("TABLE_CN >", value, "tableCn");
            return (Criteria) this;
        }

        public Criteria andTableCnGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_CN >=", value, "tableCn");
            return (Criteria) this;
        }

        public Criteria andTableCnLessThan(String value) {
            addCriterion("TABLE_CN <", value, "tableCn");
            return (Criteria) this;
        }

        public Criteria andTableCnLessThanOrEqualTo(String value) {
            addCriterion("TABLE_CN <=", value, "tableCn");
            return (Criteria) this;
        }

        public Criteria andTableCnLike(String value) {
            addCriterion("TABLE_CN like", value, "tableCn");
            return (Criteria) this;
        }

        public Criteria andTableCnNotLike(String value) {
            addCriterion("TABLE_CN not like", value, "tableCn");
            return (Criteria) this;
        }

        public Criteria andTableCnIn(List<String> values) {
            addCriterion("TABLE_CN in", values, "tableCn");
            return (Criteria) this;
        }

        public Criteria andTableCnNotIn(List<String> values) {
            addCriterion("TABLE_CN not in", values, "tableCn");
            return (Criteria) this;
        }

        public Criteria andTableCnBetween(String value1, String value2) {
            addCriterion("TABLE_CN between", value1, value2, "tableCn");
            return (Criteria) this;
        }

        public Criteria andTableCnNotBetween(String value1, String value2) {
            addCriterion("TABLE_CN not between", value1, value2, "tableCn");
            return (Criteria) this;
        }

        public Criteria andTableEnIsNull() {
            addCriterion("TABLE_EN is null");
            return (Criteria) this;
        }

        public Criteria andTableEnIsNotNull() {
            addCriterion("TABLE_EN is not null");
            return (Criteria) this;
        }

        public Criteria andTableEnEqualTo(String value) {
            addCriterion("TABLE_EN =", value, "tableEn");
            return (Criteria) this;
        }

        public Criteria andTableEnNotEqualTo(String value) {
            addCriterion("TABLE_EN <>", value, "tableEn");
            return (Criteria) this;
        }

        public Criteria andTableEnGreaterThan(String value) {
            addCriterion("TABLE_EN >", value, "tableEn");
            return (Criteria) this;
        }

        public Criteria andTableEnGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_EN >=", value, "tableEn");
            return (Criteria) this;
        }

        public Criteria andTableEnLessThan(String value) {
            addCriterion("TABLE_EN <", value, "tableEn");
            return (Criteria) this;
        }

        public Criteria andTableEnLessThanOrEqualTo(String value) {
            addCriterion("TABLE_EN <=", value, "tableEn");
            return (Criteria) this;
        }

        public Criteria andTableEnLike(String value) {
            addCriterion("TABLE_EN like", value, "tableEn");
            return (Criteria) this;
        }

        public Criteria andTableEnNotLike(String value) {
            addCriterion("TABLE_EN not like", value, "tableEn");
            return (Criteria) this;
        }

        public Criteria andTableEnIn(List<String> values) {
            addCriterion("TABLE_EN in", values, "tableEn");
            return (Criteria) this;
        }

        public Criteria andTableEnNotIn(List<String> values) {
            addCriterion("TABLE_EN not in", values, "tableEn");
            return (Criteria) this;
        }

        public Criteria andTableEnBetween(String value1, String value2) {
            addCriterion("TABLE_EN between", value1, value2, "tableEn");
            return (Criteria) this;
        }

        public Criteria andTableEnNotBetween(String value1, String value2) {
            addCriterion("TABLE_EN not between", value1, value2, "tableEn");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByIsNull() {
            addCriterion("LAST_UPDATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByIsNotNull() {
            addCriterion("LAST_UPDATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByEqualTo(String value) {
            addCriterion("LAST_UPDATE_BY =", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByNotEqualTo(String value) {
            addCriterion("LAST_UPDATE_BY <>", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByGreaterThan(String value) {
            addCriterion("LAST_UPDATE_BY >", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_UPDATE_BY >=", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByLessThan(String value) {
            addCriterion("LAST_UPDATE_BY <", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByLessThanOrEqualTo(String value) {
            addCriterion("LAST_UPDATE_BY <=", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByLike(String value) {
            addCriterion("LAST_UPDATE_BY like", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByNotLike(String value) {
            addCriterion("LAST_UPDATE_BY not like", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByIn(List<String> values) {
            addCriterion("LAST_UPDATE_BY in", values, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByNotIn(List<String> values) {
            addCriterion("LAST_UPDATE_BY not in", values, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByBetween(String value1, String value2) {
            addCriterion("LAST_UPDATE_BY between", value1, value2, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByNotBetween(String value1, String value2) {
            addCriterion("LAST_UPDATE_BY not between", value1, value2, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeIsNull() {
            addCriterion("LAST_UPDATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeIsNotNull() {
            addCriterion("LAST_UPDATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeEqualTo(Date value) {
            addCriterion("LAST_UPDATED_TIME =", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeNotEqualTo(Date value) {
            addCriterion("LAST_UPDATED_TIME <>", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeGreaterThan(Date value) {
            addCriterion("LAST_UPDATED_TIME >", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATED_TIME >=", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeLessThan(Date value) {
            addCriterion("LAST_UPDATED_TIME <", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATED_TIME <=", value, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeIn(List<Date> values) {
            addCriterion("LAST_UPDATED_TIME in", values, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeNotIn(List<Date> values) {
            addCriterion("LAST_UPDATED_TIME not in", values, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATED_TIME between", value1, value2, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATED_TIME not between", value1, value2, "lastUpdatedTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatecreationTimeIsNull() {
            addCriterion("CREATECREATION_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatecreationTimeIsNotNull() {
            addCriterion("CREATECREATION_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatecreationTimeEqualTo(Date value) {
            addCriterion("CREATECREATION_TIME =", value, "createcreationTime");
            return (Criteria) this;
        }

        public Criteria andCreatecreationTimeNotEqualTo(Date value) {
            addCriterion("CREATECREATION_TIME <>", value, "createcreationTime");
            return (Criteria) this;
        }

        public Criteria andCreatecreationTimeGreaterThan(Date value) {
            addCriterion("CREATECREATION_TIME >", value, "createcreationTime");
            return (Criteria) this;
        }

        public Criteria andCreatecreationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATECREATION_TIME >=", value, "createcreationTime");
            return (Criteria) this;
        }

        public Criteria andCreatecreationTimeLessThan(Date value) {
            addCriterion("CREATECREATION_TIME <", value, "createcreationTime");
            return (Criteria) this;
        }

        public Criteria andCreatecreationTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATECREATION_TIME <=", value, "createcreationTime");
            return (Criteria) this;
        }

        public Criteria andCreatecreationTimeIn(List<Date> values) {
            addCriterion("CREATECREATION_TIME in", values, "createcreationTime");
            return (Criteria) this;
        }

        public Criteria andCreatecreationTimeNotIn(List<Date> values) {
            addCriterion("CREATECREATION_TIME not in", values, "createcreationTime");
            return (Criteria) this;
        }

        public Criteria andCreatecreationTimeBetween(Date value1, Date value2) {
            addCriterion("CREATECREATION_TIME between", value1, value2, "createcreationTime");
            return (Criteria) this;
        }

        public Criteria andCreatecreationTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATECREATION_TIME not between", value1, value2, "createcreationTime");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DELETE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DELETE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(String value) {
            addCriterion("DELETE_FLAG =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(String value) {
            addCriterion("DELETE_FLAG <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(String value) {
            addCriterion("DELETE_FLAG >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(String value) {
            addCriterion("DELETE_FLAG >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(String value) {
            addCriterion("DELETE_FLAG <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(String value) {
            addCriterion("DELETE_FLAG <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLike(String value) {
            addCriterion("DELETE_FLAG like", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotLike(String value) {
            addCriterion("DELETE_FLAG not like", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<String> values) {
            addCriterion("DELETE_FLAG in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<String> values) {
            addCriterion("DELETE_FLAG not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(String value1, String value2) {
            addCriterion("DELETE_FLAG between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(String value1, String value2) {
            addCriterion("DELETE_FLAG not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNull() {
            addCriterion("comments is null");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNotNull() {
            addCriterion("comments is not null");
            return (Criteria) this;
        }

        public Criteria andCommentsEqualTo(String value) {
            addCriterion("comments =", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotEqualTo(String value) {
            addCriterion("comments <>", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThan(String value) {
            addCriterion("comments >", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("comments >=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThan(String value) {
            addCriterion("comments <", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThanOrEqualTo(String value) {
            addCriterion("comments <=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLike(String value) {
            addCriterion("comments like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotLike(String value) {
            addCriterion("comments not like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsIn(List<String> values) {
            addCriterion("comments in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotIn(List<String> values) {
            addCriterion("comments not in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsBetween(String value1, String value2) {
            addCriterion("comments between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotBetween(String value1, String value2) {
            addCriterion("comments not between", value1, value2, "comments");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tpl_table_mapping
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tpl_table_mapping
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}